### ISSUE TITLE
Selected text within red blocks in diff is indistinguishable from the surroinding text

### ISSUE THREAD

**Issue by teo1978** [wickedest/Mergely#104]
Steps to reproduce:

1. Go to http://www.mergely.com/a2tIf4tp/
2. Select the word "ipsum"

Expected:
the selected word should be highlighted in a way that is distinguishable from non-selected text

Observed:
the selected word is not highlighted in any way. You can't tell what text is selected.

**Comment by php4fan** [comment]
Is this extremely difficult to fix, or do you not appreciate the crippling impact it has on usability?

**Comment by wickedest** [comment]
The fix requires that you use the [mark-selection](https://codemirror.net/demo/markselection.html) addon from codemirror.

**Comment by php4fan** [comment]
This issue still exists at editor.mergely.com

**Comment by php4fan** [comment]
> This issue still exists at editor.mergely.com

Still does one year later
