### ISSUE TITLE
merge bug when \n

### ISSUE THREAD

**Issue by wolaiye1010** [wickedest/Mergely#115]
![image](https://user-images.githubusercontent.com/15831945/60498935-162f7500-9cea-11e9-9243-8828e6ef8199.png)
click merge change right
![image](https://user-images.githubusercontent.com/15831945/60499183-8938eb80-9cea-11e9-93d0-f3e415401c69.png)

**Comment by wolaiye1010** [comment]
@wickedest ,Thank you for your attention.  Excuse me? when this bug can fix？

**Comment by wickedest** [comment]
Sorry, but not for a while.  I am very busy at the moment, and I am on holiday for a week from tomorrow.

**Comment by wickedest** [comment]
@wolaiye1010 - that's fixed.  thanks for reporting the issue.

**Comment by wolaiye1010** [comment]
@wickedest , That's great！
