### ISSUE TITLE
mergely is not a function in angular 6 typescript

### ISSUE THREAD

**Issue by bhrunno** [wickedest/Mergely#116]
message :mergely is not a function. in my angular 6 project

ex:

import { Component, OnInit } from '@angular/core';
import * as $ from 'jquery';
...
ngOnInit() {
$(document).ready(function () {
    // initialize mergely
    $('#mergely').mergely();

    // set editor content
    $('#mergely').mergely({
        license: 'lgpl',
        cmsettings: {
         readOnly: true
        },
        lhs: function(setValue) {
            setValue('the quick red fox\njumped over the hairy dog');
        },
        rhs: function(setValue) {
            setValue('the quick brown fox\njumped over the lazy dog');
        }
    });
});

**Comment by wickedest** [comment]
I can't really say because I do not know Angular.  However, what you need
to do is include jquery and mergely as a jquery plugin.
This might help:
https://medium.com/all-is-web/angular-5-using-jquery-plugins-5edf4e642969

**Comment by gsaumyag** [comment]
**Solution**
Mergely requires that jQuery is global, a limitation of Mergely. I'm guessing you'll need to use it globally throughout your project as webpack doesn't want to include it twice.

Instead of:

`import * as jquery from 'jquery';`

Do this:

`declare var jQuery: any;`
