### ISSUE TITLE
Inconsistent, nonsensical rendering of diff on pasted input

### ISSUE THREAD

**Issue by teo1978** [wickedest/Mergely#118]
Steps to reproduce:
1. Visit http://www.mergely.com/biSrwsDO/
2. Copy and paste both sides of the input to a fresh new mergely window

(note that this is just a way of providing the example input. The same would happen if you copied the input from somewhere else).

Expected:
The output should look exactly like the one you see from the saved diff, which is correct

Observed:
The output you get looks like this:
![image](https://user-images.githubusercontent.com/542107/61314785-acd95700-a7fd-11e9-9503-40946498a158.png)

which makes no sense whatsoever. There are lines that are identical that on the left are striked in red as if removed, and on the right side, they are NOT highlighted in any way. If they were removed from the left, they should be added on the right (let alone they should be neither, because they are identical). If a line shows up unmarked on the right, that means it's identical to the other side, but this contraddicts the fact that the same line on the left is marked as deleted.

That's the case, for example, of these lines:
```
13 <-> 15
14 <-> 16
18 <-> 23
```

I saved the diff for sharing because I wanted to link it as an example of the issue, but to my surprise, after saving and reloading, it shows up as expected.

This issue basically renders mergely completely useless unless you save your diff every time and look at it after reload.

**Comment by wickedest** [comment]
Yep, there seems to be a problem there.  That there is something unique about your example.  The problem does not seem to manifest in other attempts.  If I take about half the lines of your example, it diffs fine.  Maybe it is a timing issue.

**Comment by teo1978** [comment]
> That there is something unique about your example. The problem does not seem to manifest in other attempts.

I see it very often lately. Usually I paste entire files (php and js files) of a few dozens or hundreds of lines.
It doesn't happen every time, but I'd say there's not a day that goes by that I use mergely and I don't stumble upon this issue.
Until a few weeks ago, I had never observed it (or never noticed).

**Comment by wickedest** [comment]
@teo1978, fixed.  thanks for reporting the issue.
