### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by pcleckler** [wickedest/Mergely#119]
Uncaught ReferenceError: require is not defined
    at mergely.js:3

...on a static web page (file:// protocol).  

To replicate, I've taken the Simple example, created the necessary "lib" folder, and loaded mergely.js, Timer.js, and mergely.css in it.

**Comment by wickedest** [comment]
which browser?

**Comment by wickedest** [comment]
Actually, I have a feeling you are using src/mergely.js.  You will not be able to use that directly - it gets compiled into lib/mergely.js.  Use the files in the lib directory.

**Comment by pcleckler** [comment]
Chrome and yep, grabbed the src version.  Thanks!
