### ISSUE TITLE
How to apply CodeMirror theme ?

### ISSUE THREAD

**Issue by lopezzlaura** [wickedest/Mergely#121]
Hi, 
I'm am using your component in Angular and everything seems to be working perfectly when it come to the diff functions and stuff but one thing I cannot manage to do is making Mergely apply the CodeMirror theme that I want to use. 
This is the config I have : 
![image](https://user-images.githubusercontent.com/33630165/62127107-8cb39880-b2d1-11e9-84a9-6ea0f18bda4c.png)

This is the display I got from it : (the background gets the right background color from the theme but no text is ever colored)

![image](https://user-images.githubusercontent.com/33630165/62127143-a654e000-b2d1-11e9-8ec4-07c2b34c0ec7.png)

If you have any idea I would really appreciate that, I have been working on it for 2 days

**Comment by wickedest** [comment]
Hi @lopezzlaura, I am sorry you are frustrated.  I have never tried to enable a theme, or syntax highlighting with Mergely.  This is because Mergely applies a lot of styles to achieve the diff.  

You should be using the option, [cmsettings](http://mergely.com/doc#cmsettings) to apply the codemirror theme.  If that doesn't work, I can recommend you use the developer console (e.g. in chrome or firefox).  Is the theme being loaded?  Inspect DOM elements to see what classes are being applied.  Maybe manually disable mergely.css and see what happens.  Mergely has an [autoupdate](http://mergely.com/doc#autoupdate) function that could be screwing with your styles.  Maybe disable it.

**Comment by lopezzlaura** [comment]
Hi @wickedest ,
I think I have found the problem, CodeMirror seems to add span and associated classes for each world of a line like so : 

![image](https://user-images.githubusercontent.com/33630165/62199891-a1049d80-b384-11e9-888e-5e477af89b0d.png)

But when it is used in Mergely, it is not working the same way apparently : 

![image](https://user-images.githubusercontent.com/33630165/62200009-d4dfc300-b384-11e9-92bf-965ef0315ae9.png)

So the text coloration does not apply, do you have any idea on how to turn on this word partition thing ? I have tried to disable autoupdate and mergely css but it is not working yet.

**Comment by wickedest** [comment]
If I get some time, I will try it myself - possibly, not until this weekend.  Maybe check that theme is even being set.  Use Mergely [cm](http://mergely.com/doc#cm) to get the codemirror editor and then [getOption](https://codemirror.net/doc/manual.html#getOption) to check the theme from it.

**Comment by lopezzlaura** [comment]
Hi,
Ok thank you very much ! I'll wait until this weekend.
Yes the options object returns the right Theme, and the theme is correctly loaded in the component.

**Comment by wickedest** [comment]
HI @lopezzlaura, I was able to get an example working with theme: midnight, and mode: sql.

1. Download the theme and mode that you want from codemirror.  I got midnight.css and sql.js
2. Include the theme and mode into your application:
```html
	<link type="text/css" rel="stylesheet" href="midnight.css" />
	<script type="text/javascript" src="sql.js"></script>
```
3. Disable mergely's background color for these two styles in mergely.css (they're questionable in the first place):
```css
/*
.mergely.c.lhs,
.mergely.c.rhs { background-color: #fafafa; }
*/
```
The result:
![image](https://user-images.githubusercontent.com/871639/62409492-43649100-b5d0-11e9-9719-1bbc13b2e64f.png)

**Comment by lopezzlaura** [comment]
Hi @wickedest,
Does it also work with Angular ? Because i've tried on my Angular project here, and unfortunately it is still not working with the disabled background.

**Comment by wickedest** [comment]
@lopezzlaura, it should work with Angular.  It's just js/css.  If you share an example of the issue, I can take a look.

**Comment by lopezzlaura** [comment]
I finally mnaged to make it work, actually on Angular the imports should be on the angular.json file and all modes needs to be imported as follow : 

![image](https://user-images.githubusercontent.com/33630165/62463810-4192fd00-b78b-11e9-8557-b999d7a247ca.png)
