### ISSUE TITLE
how can let markup(red line) show on the right?

### ISSUE THREAD

**Issue by ahuang** [wickedest/Mergely#122]
for example, the red line show on the left by default
![1](https://user-images.githubusercontent.com/730550/62679851-528c7a00-b9e8-11e9-850a-eace899e8584.png)

i want the red line show on the right, how should i do?

i find an option "rhs_margin" seem to related to my demand. 
i tried use this set {rhs_margin: 'left'} but not work.

looking forward to your reply, thanks

**Comment by wickedest** [comment]
I am not sure what you mean - like this?
![image](https://user-images.githubusercontent.com/871639/62725996-2126a500-ba0e-11e9-83d4-3af58b383aa4.png)

**Comment by ahuang** [comment]
> I am not sure what you mean - like this?
> ![image](https://user-images.githubusercontent.com/871639/62725996-2126a500-ba0e-11e9-83d4-3af58b383aa4.png)

yes, i want this result.
how to get this? use any options?

**Comment by wickedest** [comment]
Hi @ahuang, you can modify the css styles.  The the css classes are:

**.a** - added
**.c** - changed
**.d** - deleted

**lines**: The lhs is left-hand-side, and rhs is right-hand-side.  Note that Mergely interprets left-to-right, so lines can be deleted from lhs, added to rhs, or changed.

**words**: Word styles are similar, where ".d.lhs" is a deleted word, and ".a.rhs" is an added word.

So for example:
```css
.mergely.ch.d.lhs {
  background-color: #ffe9e9;
  text-decoration: line-through;
  color: red !important;
}
```

This is a style for a deleted word (from the lhs) that is red with the line-through (strike-through).  The equivalent for the rhs is:

```css
.mergely.ch.a.rhs {
  background-color: #ddeeff;
}
```

You need to play around with these styles and swap them until you get the result that you want.  In your distribution, you will find a [mergely.css](https://github.com/wickedest/Mergely/blob/master/src/mergely.css#L38) file.  You can modify it, or override them with your own css file.

**Comment by ahuang** [comment]
@wickedest thanks for you help very much! 
i got your idea and i have solved my problem by simple css style override method!
