### ISSUE TITLE
Mergely polymer failed to find id-lhs-id-rhs-canvas

### ISSUE THREAD

**Issue by abialas** [wickedest/Mergely#123]
I am trying to integrate mergely with polymer. I have a very simple template:

```js
<dom-module id="simple-mergely">
  <template>
    <div class="mergely-full-screen-8">
      <div class="mergely-resizer">
        <div id="diffeditor"></div>
      </div>
    </div>
  </template>

  <script>
      (function() {
          class SimpleMergely extends Polymer.Element {
            static get is() {
              return 'simple-mergely';
            }

            static get properties() {
              return {
                  leftText: {
                      type: String,
                      observer: '_leftTextChanged'
                  },
                  rightText: {
                      type: String,
                      observer: '_rightTextChanged'
                  },
                  _domReady: {
                      type: Boolean,
                      value: false
                  }
              };
            }

            ready() {
                super.ready();
                $(this.$.diffeditor).mergely();
                this.domReady = true;
            }

            _leftTextChanged(newValue, oldValue) {
                if (this.domReady) {
                    $(this.$.diffeditor).mergely('lhs', newValue);
                }
            }

            _rightTextChanged(newValue, oldValue) {
                if (this.domReady) {
                    $(this.$.diffeditor).mergely('rhs', newValue);
                }
            }
          }
          customElements.define(SimpleMergely.is, SimpleMergely);
      })();
  </script>

</dom-module>
```

When I try to run the page with that component I am getting the error:
Failed to find: diffeditor-lhs-diffeditor-rhs-canvas

What could be a reason for this error?

**Comment by wickedest** [comment]
I am not familiar with Polymer.  All I can really offer is that the error is here: https://github.com/wickedest/Mergely/blob/master/src/mergely.js#L1523, which might help you debug it.  The canvas is created here: https://github.com/wickedest/Mergely/blob/master/src/mergely.js#L691.  It is possible your version of jQuery is not compatible.  Or, mergely is managing its own DOM elements, maybe it is being bound too early in the Polymer lifecycle.

**Comment by abialas** [comment]
I think the problem is that my mergely component is in the shadow dom which is in another Shadow DOM. I found the post [https://stackoverflow.com/questions/55101967/getelementbyid-from-within-shadow-dom] which describes that document.getElementById returns null for nested shadow dom.
