### ISSUE TITLE
official site demo is broken, pls fix it, ths

### ISSUE THREAD

**Issue by zlzdp** [wickedest/Mergely#128]
editor.js:39 Uncaught SyntaxError: Unexpected end of input

**Comment by zlzdp** [comment]
http://www.mergely.com/editor

**Comment by wickedest** [comment]
@zlzdp, it is working fine for me.  what browser + version are you using?

**Comment by zlzdp** [comment]
Chrome v81.0.4044.113 64bit

**Comment by zlzdp** [comment]
http://www.mergely.com/editor.js
I found the js file, 
the end of source is:
$.hasData(t)&&(a=$.access(t),l=C.extend({},a),$.set(e,l))}}function It(t,e){var n=e.nodeName.toLowerCase();"input"===n&&dt.t

some Content is lost.

**Comment by zlzdp** [comment]
IE 11 also broken
Firefox v75.0 also broken

**Comment by wickedest** [comment]
It's working.  The file is fine on my end.  So, I am not sure what the problem is on your end.  Check your network, your proxy, use incognito.  It is possible the file is being downloaded using chunk-encoded, and maybe that is getting interrupted.  Maybe try to download it using CURL.

**Comment by zlzdp** [comment]
I tried close proxy, also not work.
editor.js load very very very slowly in china.
maybe china's GFW cause js file load error.
can you add CDN for static resoure? 
ths.

**Comment by zlzdp** [comment]
maybe you can restart server to resolve the file can't loaded, I also encountered same problem a long time ago, update Apache/nginx and restart it, it will be work.
thank you.
I remember, I can use it in 10 days ago.  but now it's broken.
