### ISSUE TITLE
First "difference marker" has wrong color

### ISSUE THREAD

**Issue by stla** [wickedest/Mergely#131]
Hello,

 Thank you for this amazing library. I encountered an issue. My background is black and the first "difference marker" (I don't know how to word that) is black as well, so not visible. It is at line 3 on the screenshot below, in the middle margin. This happens only for the first one. 

![mergelyIssue](https://user-images.githubusercontent.com/4466543/91291476-680c4780-e795-11ea-8984-51d7f7a3f8e9.png)

**Comment by wickedest** [comment]
Have you tried changing these styles:
.mergely.current.start { border-top: 1px solid #000 !important; }
.mergely.current.end { border-bottom: 1px solid #000 !important; }

**Comment by stla** [comment]
Thank you! Indeed, I can change the color here.
