### ISSUE TITLE
Can I obtain the number of added and deleted rows?

### ISSUE THREAD

**Issue by Robortzhao** [wickedest/Mergely#137]
Thank you so much for providing such a great tool! I read the document, but I did not see the interface for adding and deleting lines. Can this interface be provided?

**Comment by wickedest** [comment]
Just to clarify - are you looking for an API that returns the number of lines, added, removed, and modified?

**Comment by Robortzhao** [comment]
Yes！Thank you very much for your understanding！

**Comment by wickedest** [comment]
Added 'summary' method in https://github.com/wickedest/Mergely/tree/4.3.0
