### ISSUE TITLE
Changes marked up strangely when comparing differently separated lines (tabulator vs. space)

### ISSUE THREAD

**Issue by one-github** [wickedest/Mergely#139]
When I compare two lines where they differ in separation (tabulator vs. space) and have changed words, Mergely marks them up strangely.

Example:
Left (separated with tabs):
`words→separated→differently→with→changes→words→notok`

Right (separated with spaces):
`words separated differently with changed words notok`

Irrespective of the option "Ignore Whitespace", Mergely marks them up like this:

Left (strike through = red):
`w̶o̶r̶d̶s̶ ̶s̶e̶p̶a̶r̶a̶t̶e̶d̶ ̶d̶i̶f̶f̶e̶r̶e̶n̶t̶l̶y̶ ̶w̶i̶t̶h̶ ̶c̶h̶a̶n̶g̶e̶s̶ ̶words notok`

Right (font in parentheses is blue):
`words (separated differently with changed words) notok`

IMHO it should be marked up like this instead:
Left (strike through = red):
`words separated differently with c̶h̶a̶n̶g̶e̶s̶ words notok`

Right (font in parentheses is blue):
`words separated differently with (changed) words notok`

See here for an example:
https://editor.mergely.com/knqxxZM0/

**Comment by wickedest** [comment]
@one-github, thanks for reporting this issue.  I changed the inline diff to render character-by-character diff, which improves the result.  Your example, rendered with `ignorews: true`:
![image](https://user-images.githubusercontent.com/871639/135761433-4f0feb2d-a57e-4df9-b73d-2e7278ee090b.png)
and with `ignorews: false`:
![image](https://user-images.githubusercontent.com/871639/135760721-2e2612dd-1aad-45ab-aa57-3a8dcd0291db.png)
One caveat is when ignorews is true, the inline diff is by words (ignoring the spaces between), whereas when false, it is by character.  This gives the best UX.
