### ISSUE TITLE
When I compare two files again,"scrolltodiff" is still located at the previous diff,not the first diff

### ISSUE THREAD

**Issue by baobaodz** [wickedest/Mergely#151]
Recently, I have encountered a problem during the project. I would like to ask you for help.

When I compare two different files, use "scrolltodiff" to next diff ,sunch as scroll to the third diff. 
When I compare two other different files again, I expect that diff has returned to the top or recalculated. **But it is still located at the previous third place diff**. Did I miss something?  Or how to return to the first diff?

 I’d be grateful if you could help me.

**Comment by wickedest** [comment]
@baobaodz, it sounds like you're re-using the mergely context, and the current diff position is not being reset.  What are you using to "compare two other different files", are you calling [lhs](https://mergely.com/doc#lhs) / [rhs](https://mergely.com/doc#rhs) again?

**Comment by wickedest** [comment]
That should fix it.

**Comment by baobaodz** [comment]
> That should fix it.

It works.Thanks!!!
