### ISSUE TITLE
The connection line between left and right difference is displayed in unaligned situations When I zoom in/out the browser

### ISSUE THREAD

**Issue by baobaodz** [wickedest/Mergely#152]
Hello, I have some problems with alignment.
The connection line between left and right difference is displayed in alignment when the browser is 100%.
When I zoom in/out the browser , especially when I zoom in/out to 70-80%, there will be some unaligned situations. See the following figure which is 80% zooming.
![pic](https://user-images.githubusercontent.com/37931449/123207846-9a3f2080-d4f0-11eb-9903-5102f0e70aad.PNG)

Is this a problem?
ps: Google Chrome version: 91.0.4472.114

I would appreciate it if you could help me.

**Comment by wickedest** [comment]
I don't see that on https://editor.mergely.com, so I think there might be styles/fonts or elements that you added that is disrupting the alignment.  Some libraries can effect global styles/fonts.  On startup, Mergely calculates the height of a normal line and uses that for rendering.  I'd recommend you disable all styles, and libraries that are not mergely related until you find the issue.

**Comment by baobaodz** [comment]
Sorry, what I expressed may not be clear. I use the **Ctrl+mouse wheel** for scaling the page size instead of resizing the browser window. I found that when I scaled in from 100% to 80% on https://editor.mergely.com, the unaligned phenomenon was more obvious. Please try.
![diff](https://user-images.githubusercontent.com/37931449/123262317-55d07680-d52a-11eb-9b0d-f06e0bc7d3d1.PNG)

**Comment by wickedest** [comment]
@baobaodz, confirmed the issue and pushed a fix.  the issue was that mergely caches the line-height of the editor, but didn't recalculate it on resize.  usually, it doesn't have to, but clearly, when zooming, it does.  now, on resize, the line-height will be recalculated.
