### ISSUE TITLE
Does not distinguish between  `` \n `` vs `` \r\n ``

### ISSUE THREAD

**Issue by mmikeww** [wickedest/Mergely#154]
I just tested the online tool on the site. No diff is showing up when I paste in the same line with different newline endings

**Comment by wickedest** [comment]
confirmed

**Comment by wickedest** [comment]
So the issue is actually just configuration related as discussed [here](https://discuss.codemirror.net/t/does-codemirror-normalize-crlf-endings/3449).  You would need to add `lineSeparator: '\n'` to [cmsettings](https://mergely.com/doc#cmsettings).
```js
$('#compare').mergely({
	width: 'auto',
	height: 'auto',
	cmsettings: { readOnly: false, lineSeparator: '\n' },
});
```

**Comment by mmikeww** [comment]
thank you, it works

**Comment by mmikeww** [comment]
since mergely is a diff tool, probably worthwhile to somehow set a default or recommendation for users
