### ISSUE TITLE
.tgz doesn't have 'lib' folder

### ISSUE THREAD

**Issue by Dottenpixel** [wickedest/Mergely#157]
I'm attempting to do [installation via tgz](https://github.com/wickedest/Mergely#installation-via-tgz). There's referencs to files being in a `lib` folder, but there is no `lib` folder in the archive

**Comment by wickedest** [comment]
@Dottenpixel, sorry, the installation instructions for tgz were out of date.  I updated them.  Thanks for reporting it.
