### ISSUE TITLE
Update the examples on the site

### ISSUE THREAD

**Issue by hadithmv** [wickedest/Mergely#159]
On the mergely site (https://www.mergely.com/)

It shows examples under "Online Examples" from:
codepen.io
jsfiddle.net

However they use css and js files from 5 years ago, and simply changing the version causes the whole thing to break.
Kindly consider updating the examples on the site.

Thank you

**Comment by wickedest** [comment]
@hadithmv, thanks - y, the CDN was old and things a bit out of date.  The examples are updated now.
