### ISSUE TITLE
"Ignore white space" hides punctuation changes

### ISSUE THREAD

**Issue by generalmimon** [wickedest/Mergely#161]
See the screen recording below - once the "Ignore white space" option is enabled, Mergely stops highlighting changes in punctuation:

![mergely-ignore-whitespace-stops-highlighting-punctuation](https://user-images.githubusercontent.com/47499687/150109153-d52b30f5-de8e-4cb0-8585-e85c78d1bfba.gif)

Test input:

<table>
<tbody>
<tr>
<td><pre><code>Lorem [ipsum] (consectetur) {adipiscing} elit
Lorem -ipsum- \consectetur/ adipiscing: 'elit"
Lorem, ipsum. consectetur? adipiscing; elit!
2 > 1 < 3 = 300%
my.email@gmail.com</code></pre></td>
<td><pre><code>Lorem ipsum consectetur adipiscing elit
Lorem ipsum consectetur adipiscing elit
Lorem ipsum consectetur adipiscing elit
2 1 3 300
my&email~gmail°com</code></pre></td>
</tr>
</tbody>
</thead>

**Comment by wickedest** [comment]
Thanks @generalmimon, y, confirmed it's an issue.

**Comment by wickedest** [comment]
Fixed
