### ISSUE TITLE
How to force line-by-line merging?

### ISSUE THREAD

**Issue by stla** [wickedest/Mergely#163]
Hello,

  Consider this example:

![mergely](https://user-images.githubusercontent.com/4466543/150768262-1faf68da-f264-493f-b430-e11ccea91e47.png)

If I click one arrow, this replaces the *two lines* in the other side. Is it normal ? Is there an option, or something to do, to replace lines one-by-one when they are consecutive as in this example?

**Comment by wickedest** [comment]
@stla, yes, it's normal.  the changes are detected line-by-line, and changes are computed using lines.  so, these two lines represent one change.  the character changes are then computed separately for each line.  the merge methods only work on changes, not lines.  there currently isn't a way to do what you suggest - Mergely doesn't expose the "changes" so you can't really operate on them independently.

**Comment by stla** [comment]
Ok, thank you!
