### ISSUE TITLE
An error occurred  when I use the search function

### ISSUE THREAD

**Issue by Boom1597** [wickedest/Mergely#166]
I want to provide search functionality to my users, but it gives an error that "Uncaught TypeError: s.getSearchCursor is not a function". What can I do to fix this?
<img width="424" alt="picture1" src="https://user-images.githubusercontent.com/34604117/170616481-8d53c720-1130-4bb7-a8cb-f48ad84e0fbb.png">

**Comment by wickedest** [comment]
I think you need to require: codemirror/addon/search/searchcursor.js.

**Comment by Boom1597** [comment]
thanks a lot! now I can use this function to search key, but it's only support to find next key, disable to find previous, how can i do it? by the way, how can I do this using the merge library?
<img width="289" alt="image" src="https://user-images.githubusercontent.com/34604117/170909191-11a65faa-119d-4d4c-b3d3-a0384634a907.png">

**Comment by wickedest** [comment]
Huh, Mergely's documentation is wrong for [#search](https://mergely.com/doc#search).  The usage is: `search(side, query, direction)`, where `direction` is "next" or "prev".
