### ISSUE TITLE
How to download build

### ISSUE THREAD

**Issue by logut** [wickedest/Mergely#178]
The link https://mergely.com/download in the footer of the [documentation](https://mergely.com/doc) redirects to https://editor.mergely.com/

And the "Usage via CDN" doesn't tell where to download the builded files.

Are they available for download ? Is Cloudflare's CDN the official download location ?

**Comment by wickedest** [comment]
I removed the download but I seem to have forgotten about that link. I don't really want to be maintaining a tgz file and it is not best practice for distro these days. Cloudflare's CDN would be the official way to use Mergely without some kind of package manager/build/bundler. I'll leave this open as a bug to remind me I need to fix that page.

**Comment by wickedest** [comment]
@logut, I removed the download link and updated the [Usage via CDN](https://mergely.com/doc#usage-via-cdn). It was wrong, and it was also missing the CodeMirror requirements. Please refer to the link for the CDN example. Thanks for reporting the issue.

**Comment by wickedest** [comment]
@logut, also, I added a [cdn.html example](https://github.com/wickedest/Mergely/blob/master/examples/cdn.html).
