### ISSUE TITLE
When the modified difference point scrolls to the viewport, error: 'k is not defined  '

### ISSUE THREAD

**Issue by ZiggsTw** [wickedest/Mergely#183]
It was a great tool for my project, but there was a problem with it. 
This problem occurs only when the content of one of the left and right files is only modified (not  added and not deleted).

Error message :

```
configuration.3eacb321.js:811 Uncaught ReferenceError: k is not defined
    at j._sms (configuration.3eacb321.js:811:876)
    at j._lcs (configuration.3eacb321.js:811:256)
    at new j (configuration.3eacb321.js:807:23732)
    at C.addInlineDiff (configuration.3eacb321.js:835:6004)
    at M._markupLineChanges (configuration.3eacb321.js:807:18201)
    at M._renderChanges (configuration.3eacb321.js:807:14360)
    at M._scrolling (configuration.3eacb321.js:807:13361)
    at configuration.3eacb321.js:807:8961
```

Code ：

Implement basic functions according to the Upgrade module in the document.

Project information：

 - test 1（Result: Error）：
   vue@3.3.4 
   vite@4.4.5 
   mergely@5.1.0 

- test 2（Result: Error）：
   vue@2.7.7
   vite@3.0.2
   mergely@5.1.0

 - test 3 （Result: Normal）：
    vue@2.6.14
    vue-cli
    mergely@5.1.0

**Comment by ZiggsTw** [comment]
- 1 
![QQ截图20240307110458](https://github.com/wickedest/Mergely/assets/55838681/9fb1a713-829b-47d7-aaff-b663f18f972b)

- 2
![未命名1709779648](https://github.com/wickedest/Mergely/assets/55838681/3620480c-60f3-4662-b8fb-e326e3e8298d)

- 3  
![QQ截图20240307111041](https://github.com/wickedest/Mergely/assets/55838681/7468454f-4f70-4fc4-b721-314504d83440)

- 4
![未命名1709780541](https://github.com/wickedest/Mergely/assets/55838681/58e87f0f-4102-4644-8cb4-5010a0bbbfa5)

**Comment by wickedest** [comment]
Unfortunately, you gave me very little to work with - a couple of images and no context. I think this is your project. I think the issue is how you are integrating mergely with vue/vite. Perhaps it is strict mode or some JS/ES6 compatibility that you are using to compile/bundle the project.

**Comment by ZiggsTw** [comment]
> Unfortunately, you gave me very little to work with - a couple of images and no context. I think this is your project. I think the issue is how you are integrating mergely with vue/vite. Perhaps it is strict mode or some JS/ES6 compatibility that you are using to compile/bundle the project.

Sorry, I didn't explain it clearly. The problem occurred in my project, but I created multiple versions of the empty project mentioned above to locate the problem, and the problem still occurred when I was building the simplest case of merge.

**Comment by ZiggsTw** [comment]
> Unfortunately, you gave me very little to work with - a couple of images and no context. I think this is your project. I think the issue is how you are integrating mergely with vue/vite. Perhaps it is strict mode or some JS/ES6 compatibility that you are using to compile/bundle the project.

Sorry, I didn't explain it clearly. The problem occurred in my project, and I attempted to create multiple versions of Vue initialization projects to locate the problem. I found that the problem occurred in projects using Vite (including Vue3 and Vue2.7), and the way to reproduce the problem was to modify certain words in the middle of the same text.I will provide some key code screenshots：

![mergelyCode](https://github.com/wickedest/Mergely/assets/55838681/3c406e47-8998-4834-a13f-677beda98382)
![package](https://github.com/wickedest/Mergely/assets/55838681/96583193-2ab9-41e0-a0d6-5d124e1d739f)

https://github.com/wickedest/Mergely/assets/55838681/d08cd4a9-1c40-49ed-bee7-7e227303b2d0

![app](https://github.com/wickedest/Mergely/assets/55838681/677ffa44-94a4-4614-b1bf-ee8a6f48816e)

**Comment by wickedest** [comment]
@ZiggsTw, fixed - thanks for reporting the issue

**Comment by ZiggsTw** [comment]
Thank you for your reply. We hope it becomes increasingly powerful.

> @ZiggsTw, fixed - thanks for reporting the issue
