### ISSUE TITLE
$(...).mergely is not a function

### ISSUE THREAD

**Issue by jiangyuhang0506** [wickedest/Mergely#188]
version:"mergely": "^5.1.1"
code:
![image](https://github.com/wickedest/Mergely/assets/141807378/24d0b225-e6de-40b8-b6e8-1dfe22c6441e)
preview:
![image](https://github.com/wickedest/Mergely/assets/141807378/14e559b4-b744-49b2-8c40-60a78ab61464)

**Comment by wickedest** [comment]
@jiangyuhang0506, this works for me. was it working previously for you?

**Comment by jiangyuhang0506** [comment]
> @jiangyuhang0506, this works for me. was it working previously for you?

This is my first time using it and I discovered this issue

**Comment by jiangyuhang0506** [comment]
> It could be that your intended content block is not `id="mergely"`, or that you didn't include mergely in the webpack. Dunno exactly.
嗯，我用这个`$('#mergely').text()`是可以取到值的，说明`id="mergely"`是存在的，那么我已经npm install了mergely 包，但是我采用的是这样的方式
![image](https://github.com/wickedest/Mergely/assets/141807378/ad9fe00b-9d4f-4ae2-b969-0b786c0e926a)
![image](https://github.com/wickedest/Mergely/assets/141807378/fd9429ec-bd2b-469d-b41a-0157286495f9)

**Comment by wickedest** [comment]
I see now. No, 5.1.1 no longer requires jquery. I should have realized that earlier. I think you used the mergely-webpack example. I see that the mergely-webpack example is out of date and I need to update it. [This](https://mergely.com/doc#asynchronous-initialization) is how you instantiate mergely in 5.x.

**Comment by jiangyuhang0506** [comment]
> 我现在明白了。不，5.1.1 不再需要 jquery。我应该早点意识到这一点。我认为您使用了 mergely-webpack 示例。我发现 mergely-webpack 示例已过时，我需要更新它。[这](https://mergely.com/doc#asynchronous-initialization)就是在 5.x 中实例化 mergely 的方式。

The problem has been solved, thank you very much
