### ISSUE TITLE
Can I delete a publicly shared diff from https://editor.mergely.com/

### ISSUE THREAD

**Issue by SurajVerma** [wickedest/Mergely#202]
I shared a diff publicly by mistake on https://editor.mergely.com/ and I want to delete it. Is there a way to do this ? Appreciate any help.
Thank you!

**Comment by wickedest** [comment]
Yes, just click "share" again. There will be a delete button.

**Comment by SurajVerma** [comment]
Thank you so much for your response. I tried that, after I click share, it gives me "Delete Permanently" button with a warning popup, and clicking on that takes me to https://editor.mergely.com/ but if open the URL again it opens with the content.

**Comment by wickedest** [comment]
Send me the link to your document privately to ***@***.*** and
I'll take care of it.

**Comment by SurajVerma** [comment]
Hey again! the email address is obscured, I sent you the link on email id given on mergely.com contact page, I hope that is okay.
Really appreciate the help.

**Comment by wickedest** [comment]
@SurajVerma, I deleted your document and fixed the issue that was preventing you from deleting it. Thanks for letting me know about the issue.

**Comment by SurajVerma** [comment]
Thank you so much.
