### ISSUE TITLE
Still cant seem to be able to get mergely diacritical marks differentiating to show

### ISSUE THREAD

**Issue by hadithmv** [wickedest/Mergely#204]
Regarding this issue: [169](https://github.com/wickedest/Mergely/issues/169)

A fix was made and the issue closed

And while it does work on the editor page: [editor.mergely.com](https://editor.mergely.com),

When I try using the cdn files of the latest release, it doesnt seem to be applied to them:
[jsbin.com/nedozegegu/edit?html,css,output](https://jsbin.com/nedozegegu/edit?html,css,output)

I also notice that it doesn't seem to be applied on the main page either: [mergely.com](https://www.mergely.com/)

**Comment by wickedest** [comment]
> I also notice that it doesn't seem to be applied on the main page either: [mergely.com](https://www.mergely.com/)

Confirmed. I'll work on a fix for that - thanks for reporting it.

> When I try using the cdn files of the latest release, it doesnt seem to be applied to them:

No, it is in the CDN. This is from the link you sent me.

![image](https://github.com/user-attachments/assets/3cec2715-4922-4b87-915e-b5d43f320f02)

**Comment by hadithmv** [comment]
You are correct.

The issue on my end was, when I downloaded the latest release [5.3.2](https://github.com/wickedest/Mergely/releases/tag/v5.3.2), the examples/cdn.html file in it used the 5.0.0 version in the cdn link, which was why initially it appeared to me as if the fix wasn't applied.

Seems to be an issue of updating links. Feel free to close this.

**Comment by wickedest** [comment]
main site updated
