### ISSUE TITLE
Install from bower

### ISSUE THREAD

**Issue by sjrct** [wickedest/Mergely#21]
I think it would be nice to be able to easily install mergely as a bower dependency. There is a repo, [erahhal/bower-mergely](https://github.com/erahhal/bower-mergely), that provides that functionality but it is quite out of date as of now. I would suggest a bower.json in this repo, as it would assure that it remains up to date in the future. I could draw one up if there is no opposition.

**Comment by wickedest** [comment]
Hi Chris,

Thanks for your email.  I'm not opposed, but it was set up for me, so I
sent an email to the guy that set it up.  I'll let you know what the story
is soon.

Jamie

**Comment by sjrct** [comment]
Thanks for the merge of PR #23.
