### ISSUE TITLE
update bower to have the latest Mergely version

### ISSUE THREAD

**Issue by aadrian** [wickedest/Mergely#24]
Please submit to Bower the latest version of Mergely. Right now it seems to contain only an old one (3.3.6)

Thank you.

**Comment by wickedest** [comment]
It's complicated - someone else created it.  I've asked them to unregister so that I can control bower revisions.

**Comment by aadrian** [comment]
> It's complicated - someone else created it. ...

OK.

In the mean time, as a temporary workaround, users can reference the Tag directly in ```bower.json```:
```json
  "dependencies": {
    "mergely": "https://github.com/wickedest/Mergely.git#3.3.9"
  }
```

**Comment by wickedest** [comment]
Done
