### ISSUE TITLE
Readonly but merge?

### ISSUE THREAD

**Issue by aadrian** [wickedest/Mergely#27]
How to make the edit panes "read-only" for user edits (with the keyboard), but allow the merge operations.
If I set:
```JavaScript
...
cmsettings: {
    readOnly: true,
    lineNumbers: true 
},
...
```
the merging buttons/actions on each side disappear too, so the merging operations are not possible anymore.

Thank you.

**Comment by wickedest** [comment]
Try this:
```
lhs_cmsettings: {
    readOnly: true,
    lineNumbers: true 
},
```

**Comment by aadrian** [comment]
@wickedest 
In this case, the right side is still editable by the keyboard :(.

I would like to allow merge operations only, e.g. from left to right by allowing the uses to click the distinct merge buttons on the side, but not allow them to edit manually the right side.

**Comment by hansgru** [comment]
Any news on this bug?

We also need to "merge" with Mergely, but not allow the user to edit the panes since it could bring the result in an inconsistent state.

**Comment by wickedest** [comment]
codemirror controls the read-only pane; Mergely merely enables/disables it.  I am not aware of any way to a) allow merges via a codemirror edit method; b) disable typing.  Maybe ask on the codemirror site.

**Comment by hansgru** [comment]
Isn't the "merge" done by Mergely? Those merge buttons on the side too that trigger the merge?

**Comment by wickedest** [comment]
Yes, Mergely buttons _triggers_ the merge, but it just invokes codemirror [replaceRange](https://codemirror.net/doc/manual.html#replaceRange).  I haven't tried it, but if the doc is read only, then I doubt that method will work.

**Comment by hansgru** [comment]
> but it just invokes codemirror replaceRange

can't you simply "replace" the entire "content" of the right pane? This should work in read-only mode too. It would be like the "initial" set.

**Comment by wickedest** [comment]
In that case, you can just take the entire content of the left pane - it is equivalent to replacing the entire content of the right with the left.

**Comment by hansgru** [comment]
> In that case, you can just take the entire content of the left pane - it is equivalent to replacing the entire content of the right with the left.

Nope. I just one to merge one or a few lines (as the user wishes, or on what merge line buttons is he clicking). 
I mean that if Codemirror does not let you to perform the "replaceRange" operation on a readOnly pane, than when you can do "replace all" , i.e. set the right panel with the entire buffer (not the left buffer but what you merged with your algorithm).
