### ISSUE TITLE
Live JSFiddle example.

### ISSUE THREAD

**Issue by aadrian** [wickedest/Mergely#28]
Please add a JSFiddle example of Mergely.

This would allow users to try it right away, but would be also much easier
this way to send bug test cases by just forking and modifying that example.

Thank you.

**Comment by wickedest** [comment]
That's a good idea.  Now, why didn't I think of that...

**Comment by Sphinxxxx** [comment]
Here is a small CodePen which could be a starting point:
http://codepen.io/Sphinxxxx/pen/grVvjG

**Comment by wickedest** [comment]
Thanks!  I couldn't actually get that working in jsfiddle.  Never thought
to try codepen.  I will definitely make use of that.

Much appreciated,
Jamie

**Comment by wickedest** [comment]
Totally forgot about this thread!  Very sorry, but thanks a million for the
jsfiddle example.  Added both examples to http://mergely.com.
