### ISSUE TITLE
Mergely with Bootstrap?

### ISSUE THREAD

**Issue by hansgru** [wickedest/Mergely#30]
How to combine Mergely with Twitter Bootstrap?

I have a ```editor_width: '500px'``` setting for mergely but how can I make it to take the entire width available by Bootstrap?
e.g. 
```html
<div id="compare" class="col-sm-12"><div>
```
seems to ignore the width exposed by the '.col-sm-12'
IMHO there should be more a "min_editor_width" setting.

**Comment by wickedest** [comment]
The width can be tricky because size/dimensions are so integral to how Mergely works.  I would suggest using the size example as a starting point: http://www.mergely.com/Mergely/examples/size.html
