### ISSUE TITLE
"Ignore white space" does not ignore newlines

### ISSUE THREAD

**Issue by canac** [wickedest/Mergely#31]
Even when the "Ignore white space" menu option is selected, extra and/or missing newlines are marked as differences in the editor, which is not the behavior that I would expect.

**Comment by wickedest** [comment]
You're right - it doesn't appear to be working at all.  Even white space in lines.  I'll look into it.

**Comment by wickedest** [comment]
Sorry it took so long to get back to you.  I investigated this and it works as expected.  If you try the same with GNU diff to ignore whitespace (-w) , you will see that newlines are also marked as differences.

**Comment by waldyrious** [comment]
Can there be an extra option to also ignore newlines? It's very useful especially for text that is hard-wrapped.
