### ISSUE TITLE
[Suggestion, UX] make the diff indicators filled in with color.

### ISSUE THREAD

**Issue by marcinkuzminski** [wickedest/Mergely#34]
Hi,

I want to make a small suggestion, could it be possible to fill in the diff inidicators with a solid color ?

On large screens very thin lines are hard to see. When the diff block indicators would be filled in it would make the visibility much better.

Please see screenshot.

![screen shot 2015-11-09 at 12 31 54](https://cloud.githubusercontent.com/assets/163648/11032708/f234151e-86dd-11e5-8aba-eaac1fff79c0.png)

**Comment by wickedest** [comment]
Adding colour to so many change sets can actually be distracting.  Instead, I improved UX in this area with Mergely 3.4.0.  The current selected change is highlighted in black, and the line numbers appear in dark, which is an improvement.
