### ISSUE TITLE
HTTPS/SSL (Roadplan item) for http://www.mergely.com/editor

### ISSUE THREAD

**Issue by 3wh** [wickedest/Mergely#35]
Hi Jamie,

To start, Mergely is great!!

in your roadplan you mention SSL.

Starting on 03/12, Let's Encrypt, an initiative from the Linux Foundation, starts to handout free-of-charge HTTPS certificates.

This could be a free, automated and open solution to tackle that item on the Mergely roadplan.

--> https://letsencrypt.org/

**Comment by wickedest** [comment]
Done.  Had to switch hosting providers.  https://editor.mergely.com
