### ISSUE TITLE
Insert diff above or below

### ISSUE THREAD

**Issue by sisao** [wickedest/Mergely#36]
Hi,
is it possible to merge/insert a diff line above or below the opposite reference line?
Like in Meld with pressing the Ctrl-key?

Regards,
Stefan

**Comment by wickedest** [comment]
Hi Stefan,

No, Mergely cannot do that.  I'm not sure about the value of such a
feature.  I looked at the Meld website to see what the feature actually
did, but could not find any reference to it.

Jamie

**Comment by sisao** [comment]
Np,
I find it useful sometimes if you have to solve merge conflics...

fyi:
http://meldmerge.org/help/file-changes.html

2015-12-24 9:33 GMT+01:00 wickedest <notifications@github.com>:

> Hi Stefan,
>
> No, Mergely cannot do that. I'm not sure about the value of such a
> feature. I looked at the Meld website to see what the feature actually
> did, but could not find any reference to it.
>
> Jamie
>

**Comment by wickedest** [comment]
From the page you gave me, Mergely has equivalents.  You can navigate
between changes using Alt-Down Arrow, and Alt-Up Arrow.  You can
merge-right and left using Alt-Right Arrow and Alt-Left Arrow.
