### ISSUE TITLE
Can I Use This As A Viewer With A Different Back End?

### ISSUE THREAD

**Issue by opticyclic** [wickedest/Mergely#43]
I have quite complex requirements for what constitutes a diff or not in XML.
For this purpose I am using xmlunit as it gives me a lot of flexibility.

Is it possible to take the output of my xmlunit result and tell mergely what constitutes a diff?
i.e. just use the mergely viewer and not the mergely difference engine

**Comment by wickedest** [comment]
Sorry - it is not possible to give Mergely a diff as the engine is
baked-in.  I am in the middle of refactoring (very slowly) that would allow
that, but it's some time off.

Jamie
