### ISSUE TITLE
XML Compare Is Misleading

### ISSUE THREAD

**Issue by opticyclic** [wickedest/Mergely#45]
The about page says `It can be embedded within your own Web application to compare files, text, C, C++, Java, HTML, XML, CSS, and javascript.`
http://www.mergely.com/about

When I compare 2 xml files with attributes in different order or tags in different order mergely marks these as differences when in fact they are identical in terms of xml.

Is it in fact only doing a basic text diff?

Are there plans for proper xml diff?

**Comment by wickedest** [comment]
It is a text diff only.  I have no plans to make an xml diff.

**Comment by opticyclic** [comment]
Can you update the about page to clarify this a bit more then please.
Since it specifies text and XML separately on the about page it was confusing to me and looked like it was xml diff.
