### ISSUE TITLE
The confirmation of licenses version

### ISSUE THREAD

**Issue by Piicksarn** [wickedest/Mergely#47]
Hi :grinning: 
I would like to obtain Mergely in **[cdnjs](https://github.com/cdnjs/cdnjs)**, however, it requires accurate version of licenses.
Would you mind to provide the accurate version of licenses?
Thank you!

The link below is the license list which **cdnjs** followed :
**https://spdx.org/licenses/**

**Comment by cikasfm** [comment]
@wickedest I asked @Piicksarn to add Mergely to CDNJS for easy usage. Can you please confirm the exact license to this can be done? Thanks!

**Comment by wickedest** [comment]
Sorry for the delayed response.  Forgot about this request.  You can use LGPL.

**Comment by Piicksarn** [comment]
@wickedest, because cdnjs follows [SPDX](https://spdx.org/licenses/), we need to know the version of license.
LGPL-2.0, LGPL-2.1 or LGPL-3.0?
Thanks!

**Comment by wickedest** [comment]
LGPL-3.0

**Comment by Piicksarn** [comment]
@wickedest, cdnjs could add all licenses you mentioned above, if the version of MPL and GPL be provided.
We could include the library with multiple licenses.

**Comment by wickedest** [comment]
LGPL-3.0, MPL-2.0, GPL-3.0+
