### ISSUE TITLE
Examples don't prepopulate the .txt files

### ISSUE THREAD

**Issue by mmikeww** [wickedest/Mergely#52]
The included /examples/ include some .txt files which I assume the browser is supposed to read and pre-populate the lhs/rhs diff panes, but they don't seem to load in any of my browsers: Chrome, Firefox, IE

**Comment by wickedest** [comment]
Are you serving the examples through a web server or just opening the .html
files?

**Comment by mmikeww** [comment]
Just opening the files through my browser..
