### ISSUE TITLE
Merged Output

### ISSUE THREAD

**Issue by matthiasg** [wickedest/Mergely#53]
I love this library. Really well done ! It is the first I found that comes close to Apple's FileMerge.

FileMerge also shows an (editable) bottom area of the merge results, which is extremely helpful for understanding the final result and even allows to edit that merge block (basically overriding that sections output). Is this something that will be added sometime ?

![](https://www.git-tower.com/blog/content/posts/55-diff-tools-mac/filemerge.png)

**Comment by wickedest** [comment]
I'm glad you find Mergely useful.  I have never seen FileMerge, but if I
understand you correctly, the third editor at the bottom seems superfluous
to me.  It is exactly the same as an editable right-hand column.  I have no
intention of adding this to Mergely, but it could be built using Mergely.
Thanks - I am glad to see a new approach to diff that I haven't seen before.

**Comment by matthiasg** [comment]
Yeah great project of yours.

The output at the bottom shows the result of the merge without needing to understand which part you picked. In FileMerge you pick left/right/both from the two columns and and the bottom you can (if so desired) edit the final output. Basically the bottom is the WYSIWYG section. Which is very easy to understand to laymen (which we target). That combined with collapsing out unnecessary/unchanged sections would be the perfect diff tool for our use case. Of course that doesnt mean this is also yours :)
