### ISSUE TITLE
Feature request: Git diff

### ISSUE THREAD

**Issue by KeyWeeUsr** [wickedest/Mergely#54]
I noticed there's already `Save .diff` option available, but it has some kind of unknown syntax to me. Would it be possible to implement more export options for saving diffs, for example git diff? Yes, I know I can just use git, or if I'm online I can go play with github's diff, but Mergely provides a very nice split diff where you can merge stuff in both directions. For github, or real code editor I'd need to:

* edit the line
* save
* `git diff` again
* check if it's actually the diff I want and then export to file

and there's only one-side merge option if I don't want to copy the exact lines of code.

With this feature available I could just dump what I edit in Mergely right to the `.patch` file and send away.

**Comment by wickedest** [comment]
This is a very good idea, and I spent a bit of time digging into it.  The format that Mergely uses is the GNU [normal diff format](http://www.gnu.org/software/diffutils/manual/html_node/Normal.html).  git uses a [unified format](https://en.wikipedia.org/wiki/Diff_utility#Unified_format), but it has a special header specific to git that encompasses the change log, e.g.:
```
diff --git a/lib/mergely.css b/lib/mergely.css
index ab257f7..b9f9d66 100644
```

Notice the change SHA and paths?  It isn't possible for Mergely to fake these.  I did a fair bit of digging about applying GNU patch files using git, but they're different tools.

To apply the GNU diff file from Mergely to a file in git, you can just use the GNU `patch` command.

**Comment by KeyWeeUsr** [comment]
Oh, I know about the header, but I thought about having the git format available too. However, it seems that even the `index` line with hash (not only `diff --git` is necessary. Doesn't matter though, as gnu patch is available with git itself in msys even on Windows, so this feature request is probably redundant.
