### ISSUE TITLE
Where are PHP files accessed with AJAX from editor/editor.js ?

### ISSUE THREAD

**Issue by mnemonicflow** [wickedest/Mergely#58]
Hello,

I cannot find where is the source code for the following PHP files access from:
```
editor/editor.js
168:                            url: '/ajax/handle_get.php',
178:                            url: '/ajax/handle_get.php',
427:                            url: '/ajax/handle_file.php',
432:                                            var url = '/ajax/handle_save.php?key=' + key;
476:                    url: '/ajax/handle_crossdomain.php',
```

The menu options do not work without them.

Any ideas?

**Comment by wickedest** [comment]
They are not released.  They are specific to how I host Mergely's editor.  When you host it, you will have similar APIs to handle the operations that you wish to support, e.g. to read/write from a database.

**Comment by mnemonicflow** [comment]
I just updated to the latest Mergely from master. I've been on a previous version for some time. But I remember the Share option working without these files existing.
