### ISSUE TITLE
How to keep the cursor position unchanged

### ISSUE THREAD

**Issue by tanqinwang** [wickedest/Mergely#61]
When you enter a character, the cursor always returns to the beginning of the line.
So I have to undo and redo, so that the characters can be entered normally.
Is there a more effective way??

**Comment by wickedest** [comment]
Strange - it works on http://www.mergely.com/editor.  Are you having trouble with the online version, or if you are using the component, are you using your own version of CodeMirror?

**Comment by tanqinwang** [comment]
when i opened  [http://www.mergely.com/editor](http://www.mergely.com/editor), then click left panel, enter  'file', the got 'lefi', the cursor stay after the letter 'e', it's only happened in the first time, when i deleted it, re-entered , it works.

**Comment by wickedest** [comment]
I think you might be referring to this issue - if I open the editor, wait
for it to finish loading, and then type 'e', the cursor does not stay at
the end, e.g. "e|" - it changes to the first position "|e".  Yes?  I have
seen that issue.

**Comment by tanqinwang** [comment]
Yes, that's right. Is there a way to correct it?

**Comment by tanqinwang** [comment]
Anyway, thank you for your reply.

**Comment by wickedest** [comment]
fixed issue #95
