### ISSUE TITLE
Can it sign diff only?

### ISSUE THREAD

**Issue by Dumbass-Kk** [wickedest/Mergely#66]
I paste some words that may have '/t' in a word, then '/t'  will be convert a label of span, so if it has a diff, The whole sentence will be signed, how can l t solve this   ##problem?

**Comment by wickedest** [comment]
I do not understand the problem.  Is there an issue specifically with rendering `/t`?  If you are only looking for the .diff, you can use this method: http://www.mergely.com/doc#mergely-diff
