### ISSUE TITLE
Change tracking

### ISSUE THREAD

**Issue by salarmehr** [wickedest/Mergely#68]
I appreciate developing this really handy project. 

Instead of merging I need to use Megely for change tracking. In the same way that it works in MS word or Google Docs.

I need to present the user a single text editor pre-filled with some paragraphs and once user start typing he sees changes real-time and in-line. 

Can you please advise how can I achieve this result please?

**Comment by salarmehr** [comment]
And in the live editor, additions are one one site and deletion on the other side, is there any way to see all changes in one site?

**Comment by wickedest** [comment]
Well, Mergely can't do MS word or google style changes.  You would be looking for a different type of application entirely.  Also, Mergely does not have a single view for all changes.
