### ISSUE TITLE
"Ignore whitespace" is broken

### ISSUE THREAD

**Issue by teo1978** [wickedest/Mergely#71]
With the option "Ignore whitespace" enabled, these should be considered identical

![image](https://user-images.githubusercontent.com/542107/33040434-5a85af82-ce3b-11e7-94ce-2795c1414f55.png)

**Comment by teo1978** [comment]
I see, newlines are not considered whitespace at all. Even a different number of consecutive newlines is considered as a difference.
That sucks. Either newlines should be considered as whitespace characters, or there should be a separate option (only available when "ignore whitespace" is enabled) for whether to treat newline characters as whitespace.

**Comment by wickedest** [comment]
The "ignore whitespace" feature works as designed, equivalent to `diff -w`.  There is no option to ignore blank lines, equivalent to `diff -B`.

**Comment by teo1978** [comment]
> The "ignore whitespace" feature works as designed

And the reason why that is a good design is...?

> There is no option to ignore blank lines, equivalent to diff -B

Well that would be a great starting point.

However, correct me if I'm wrong, that still wouldn't make the two files in my example be considered as equal, right?

**Comment by wickedest** [comment]
> And the reason why that is a good design is...?
> Well that would be a great starting point.

^ Kindly ease-up on the snarky remarks.

Mergely works like lots of diff tools - by tokenizing the lines by newlines, and then finding those lines that are different.  It does not have an option to compare character-by-character, which would be computationally expensive (but theoretically possible).  So, no, your example would not be equal in Mergely.
