### ISSUE TITLE
Compare docx file, the file content garbled

### ISSUE THREAD

**Issue by Mark-ju** [wickedest/Mergely#72]
When I use the online file comparison, select two docx files for comparison, after the success of the upload file content becomes garbled, there any solution to garbled problem?

**Comment by wickedest** [comment]
It should be utf-8 https://github.com/wickedest/Mergely/blob/master/editor/editor.js#L513.

**Comment by Mark-ju** [comment]
I use the online document contrast, when compared doc file garbled, UTF-8 format or there will be garbled phenomenon. Can you modify the code below? Make it possible to achieve online comparison of doc files.

**Comment by Mark-ju** [comment]
I use the online document contrast, when compared doc file garbled, UTF-8 format or there will be garbled phenomenon. Can you modify the code below? Make it possible to achieve online comparison of doc files.

**Comment by wickedest** [comment]
It is non-trivial for Mergely to detect the international encoding of your document.  It might be possible to modify the editor to allow you to manually set the encoding, but there are hundreds of them.  The easiest thing is to save your docx (XML) document as UTF-8 and compare.
