### ISSUE TITLE
mergely appears all squeezed up in a corner until i open developer tools

### ISSUE THREAD

**Issue by beingbing** [wickedest/Mergely#74]
![screen shot 2018-01-22 at 11 56 31 am](https://user-images.githubusercontent.com/26813160/35207905-77556650-ff6b-11e7-8da1-03c4b29c312e.png)
this is how mergely appears by default, when i open the window.

and once i open the developer tools, it takes the desired size.
![screen shot 2018-01-22 at 11 56 51 am](https://user-images.githubusercontent.com/26813160/35207944-a6d24c36-ff6b-11e7-839a-3b59655b8e41.png)

p.s. - i haven't used any custom css and whatever css is coming with mergely by default, it's using that only.

**Comment by wickedest** [comment]
Sorry for the delay in responding - I've been travelling.  I think what might be happening is that you did not create a div to set the size/extents of your editor.  E.g.:
https://github.com/wickedest/Mergely/blob/master/src/mergely.css#L10

And the "mergely-full-screen-8" example here:
https://github.com/wickedest/Mergely#installation-via-tgz

If I'm wrong, then please post your HTML code and how you initialize (javascript) here.
