### ISSUE TITLE
Ctrl+F find doesn't work

### ISSUE THREAD

**Issue by teo1978** [wickedest/Mergely#78]
Steps to reproduce:

- copy and paste (or maybe even type) something in one of the two textareas
- hit ctrl+f
- enter a string that you know is in the text

Expected: should find it
Observed: doesn't find shit.

![image](https://user-images.githubusercontent.com/542107/40249211-9160089e-5ad2-11e8-979f-b6bf9c9b5c96.png)

**Comment by wickedest** [comment]
thanks! fixed
