### ISSUE TITLE
Unmergeable when one file has trailing newline

### ISSUE THREAD

**Issue by Senic** [wickedest/Mergely#79]
Hello there, 
I have a problem when trying to merge files with one of them ending on a newline. 

Reproduce steps:
- go to http://www.mergely.com/editor
- Fill in left text:
```
text

```
(with trailing newline)
- Fill in right text:

```
text

more text
```
- merge from left to right.
At the first merge it will remove the "more text" line from the right side. After that it gets stuck and you cannot finish the merge

Example of files:
<img width="808" alt="screen shot 2018-05-22 at 15 51 47" src="https://user-images.githubusercontent.com/2477162/40366792-4aff338a-5dd8-11e8-8c70-f610c145519f.png">

Hope you can help.

**Comment by wickedest** [comment]
Y, can reproduce.  Seems that it has trouble merging an add/remove when it is the last line.  Direction doesn't matter.

**Comment by wickedest** [comment]
Fixed in 4.0.2
