### ISSUE TITLE
Performance degradation: becomes unusable with just a few thousands lines

### ISSUE THREAD

**Issue by teo1978** [wickedest/Mergely#83]
I'm comparing two files that are only about 8000 lines longs, which should be considered ridiculously small. There are about.... (wait a moment, there's not even a total count of differences, insertions and deletions anywhere?? Whatever)... anyway, the differences are a small percentage of the contents: every 5-10 lines or so there's a line that differs partially.

The editor is so slow in responding (e.g. to scrolling) that it's completely unusable.

I don't expect hugely optimized performance, but if the tool becomes unusable with a file as small as a few thousands lines of which maybe 10% differ, there's definitely something wrong.

**Comment by wickedest** [comment]
Fixed
