### ISSUE TITLE
merge button disappears in 4.0.5

### ISSUE THREAD

**Issue by ja8zyjits** [wickedest/Mergely#89]
Hi,

I downloaded the latest version of mergely and the merge button disappeared. I wanted it the way it was shown in [codepen eg](https://codepen.io/Sphinxxxx/pen/grVvjG). Later with few debugging I replaced the [current updated version](http://www.mergely.com/mergely.tgz) i.e 4.0.5 with the one shown in code pen i.e 3.4.1(who's cdn seems to have moved and now showing 301 error in srihash.org) and it seems working.

**Comment by wickedest** [comment]
Yes it does.  Had a quick look and under the hood, all looks okay.  I am not sure what the issue is.
