### ISSUE TITLE
Upload local file

### ISSUE THREAD

**Issue by rg-cse** [wickedest/Mergely#92]
How can I upload local file like the DEMO in the editor ? I tried with local fakepath but it's not happening.

**Comment by wickedest** [comment]
There is an example: http://www.mergely.com/node_modules/mergely/examples/ajax.html
The [source](https://github.com/wickedest/Mergely/blob/master/examples/ajax.html).

**Comment by rg-cse** [comment]
Thank You , however when I am uploading .docx file it is not showing up properly. It is fine with the .txt files.

**Comment by wickedest** [comment]
Mergely only supports text file formats, e.g. .txt, .css, .html, .xml, etc.  .docx is a binary format.
