### ISSUE TITLE
Diff highlighting stops working when Find is in use

### ISSUE THREAD

**Issue by teo1978** [wickedest/Mergely#94]
Steps to reproduce:
1. Paste some two similar but not identical long texts about the same size into the left and right editors. Make sure there are differences here and there from the beginning to the end and that the text is much longer than what fits in the textareas
2. Click within one of the two editors, e.g. the one on the left and hit Ctrl+F to start searching for a substring
3. Type something that will have matches
4. Now scroll down

Expected result:
Obviously, the highlighting of differences between the two texts should keep working as usual after you scroll, regardless of whether the Ctrl+F search box is active or not

Observed result:
while the Find box is visible, the diff highlighting is completely broken. When you scroll, anything that is outside the initially visible area and comes in as you scroll, is not highlighted. The connecting lines between the two textareas remain frozen as they where before you started scrolling, instead of moving and updating based on the scrolled content.

When you close the Find box, diff highlighting resumes working as expected.

![bug_mergely](https://user-images.githubusercontent.com/542107/44104964-86304336-9ff0-11e8-808e-c89b1a667f67.png)

**Comment by wickedest** [comment]
confirmed

**Comment by teo1978** [comment]
So should I report it elsewhere?

**Comment by wickedest** [comment]
No, it's fixed - sorry, wasn't clear.
