### ISSUE TITLE
Chinese comparison question

### ISSUE THREAD

**Issue by Andseny** [wickedest/Mergely#96]
First of all, thank you for letting me know and use such a good plug-in.Now, I have a problem,The contrast between Chinese and English is not the same.When I enter Chinese, if I encounter a difference, there will be a delete line in the whole paragraph,In English, there is a marked word.(As shown in the picture) Is there any way to optimize it?So that Chinese can also get better contrast effect.
Thank you again！

ps:
同时，也求助各位国人，有遇到同样问题的吗？就是中文与英文的对比效果不同，当我输入中文时，如果遇到不同，则整个段落都会出现删除线，而英文状态下，则是某个单词会有明显标记。有什么办法处理吗？如下图所示：

![default](https://user-images.githubusercontent.com/22341148/44194140-abc02580-a167-11e8-898e-d9e161ccc720.png)

**Comment by wickedest** [comment]
Currently, Mergely compares and highlights words.  In order to improve rendering of Chinese, it would be necessary to add an enhancement to display diffs by character.

**Comment by Andseny** [comment]
OK, thank you again, and look forward to a better creation.

**Comment by laocu** [comment]
老哥，我运行代码样例光标会有乱码，你知道是咋回事吗
![Uploading image.png…]()

**Comment by mww-cloud** [comment]
HI, wickedest, 

It is possible just change diff algorithm on Mergely?
or maybe allow input diff format data like google diff?

when i try this: https://neil.fraser.name/software/diff_match_patch/demos/diff.html
if input Chinese : "中文測試" vs "中文不試" , and select  [No Cleanup] option, 
the result will be "中文**測**_不_試".  it can work for single Chinese char.

**Comment by wickedest** [comment]
It is an enhancement I would like to do.  It's on the list, but I cannot say when it will be done.

**Comment by mww-cloud** [comment]
Appreciate！
